### PR TITLE
First commit to landscape.yml

### PR DESCRIPTION
**Pull request by MordodeMaru**
Please review this first commit to see if it's in line with what is expected. This project did not have an SVG image of its logo so I created one with an online converter that actually hosts the new SVG file. Please let me know otherwise.

I've left the Crunchbase link section empty because Augur Labs doesn't have a Crunchbase profile.

### Pre-submission checklist:

*Please check each of these after submitting your pull request:*

* [x] Are you only including a `repo_url` if your project is 100% open source? If so, you need to pick the single best GitHub repository for your project, not a GitHub organization.
* [x] Is your project closed source or, if it is open source, does your project have at least 250 GitHub stars?
* [x] Have you picked the single best (existing) category for your project?
* [x] Does it follow the other guidelines from the [new entries](https://github.com/cncf/landscape#new-entries) section?
* [x] Have you included a URL for your SVG or added it to `hosted_logos` and referenced it there?
* [x] Does your logo clearly state the name of the project/product and follow the other logo [guidelines](https://github.com/cncf/landscape#logos)?
* [x] Does your project/product name match the text on the logo?
* [x] Have you verified that the Crunchbase data for your organization is correct (including headquarters and LinkedIn)?
* [x] ~10 minutes after opening the pull request, the CNCF-Bot will post the URL for your staging server. Have you confirmed that it looks good to you and then added a comment to the PR saying "LGTM"?

### CODE REVIEW

**Comment by MordodeMaru** [comment]
@tracymiranda @kestewart if you could check this I'll proceed with the rest when I have time.

**Review by kestewart — APPROVED** [review]
Looks good to me, but defering to @tracymiranda as she's more of an expert here than me.

**Comment by tracymiranda** [comment]
Although the logs seem to complain about the github repo, I'm inclined to think the issue here is the logo. I'm not sure it will work referenced from the gdrive link - could we try checking in the svg to the 'hosted logos' folder and then referencing it by name.

**Comment by tracymiranda** [comment]
You can't commit directly to the main repo, you have to add the file to your fork/branch where you made the other changes. @MordodeMaru

**Comment by MordodeMaru** [comment]
I believe my patch should now include the changes to the logo folder where I have uploaded Augur's logo in SVG format. @tracymiranda

**Comment by tracymiranda** [comment]
Hmm the build still failed - this time complaining about the repo: https://github.com/chaoss/augur/.
The repo exists so not sure why this is an issue @AndreyKozlov1984 wonder if any ideas?

**Comment by tracymiranda** [comment]
@MordodeMaru looks like you just need to remove the trailing slash from https://github.com/chaoss/augur/ and we should be good to go

**Comment by MordodeMaru** [comment]
Done.

**Comment by tracymiranda** [comment]
Spoke too soon, looks like there are 2 failing issues in the logs:

6:31:04 AM: FATAL: We do not support urls for images anymore. Please download the image and put it into the hosted_logos folder, then put its name to the logo field
6:31:06 AM: FATAL: Augur either has no crunchbase entry or it is invalid

**Comment by MordodeMaru** [comment]
I don't understand. The logo is in fact in the hosted_logos folder, see below. I don't what to do about the crunchbase entry. I've left it empty because, well, there isn't one. What should I have done? @kestewart 
CleanShot 2023-08-03 at 16 37 04

**Comment by tracymiranda** [comment]
Yes but you need to update the logo field so it isn't pointing to the drive anymore but has the name of the svg file. 
Also looks like a crunchbase entry is required

**Comment by MordodeMaru** [comment]
With the help of Andrey Kozlov from the CNCF I think I amended the two things that were wrong. 🤞🏻

**Comment by MordodeMaru** [comment]
So the logo I was trying to push was empty god knows why. I am faily sure I did it right but hey, who am I to argue with Git. Having said that, I deleted the empty logo and now I think that the only solution is to close this PR, open again a fork and push it back this time with the logo in it properly.

**Comment by tracymiranda** [comment]
I think the plan to close this PR is good. I see the new one with the logo has succeeded.

**Pull request closed without merging**
